version: '3.8'

services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DATABASE}

    ports:
      - 5432:5432

    user: postgres

    networks:
      - grepsr_shared-network
    
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      # - ./postgres-db:/var/lib/postgresql/data
      
    
  node_api:
    container_name: conduit_api
    restart: on-failure
    image: conduit-api-prod:1.0.0
    build: 
      context: Conduit_NodeJS
      target: production
      dockerfile: Dockerfile
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - PORT=${PORT}
      - DATABASE=${DATABASE}
    
    expose:
      - 8080

    networks:
      - grepsr_shared-network
    ports:
      - 8080:8080
    depends_on:
      - postgres

  client:
    container_name: conduit_client
    restart: unless-stopped
    image: conduit-client-prod:1.0.0
    build: 
      context: next-realworld-example-app
      target: production
      dockerfile: Dockerfile
    
    expose:
      - 3000

    links:
      - node_api

    networks:
      - grepsr_shared-network
    ports:
      - 3000:3000
    depends_on:
      - node_api

networks:
  grepsr_shared-network:
    