name: Build Docker Images and Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose up -d

    - name: Run Postman Tests
      run: npx newman run Conduit.postman_collection.json --delay-request 500 --global-var "APIURL=http://localhost:8080/api" --global-var 	"USERNAME=shyambh" --global-var "EMAIL=bhattaraishyam@gmail.com" --global-var "PASSWORD=Test123$"
      working-directory: Conduit_NodeJS

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v2
      with:
        spec: next-realworld-example-app/FunctionalTests/login.spec.js
      # run: npx cypress run --spec ./FunctionalTests/login.spec.js
      # working-directory: next-realworld-example-app
     